### ISSUE TITLE
Add Kong to scenario

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/containo#1]
Add Kong to the current scenario.

- [ ] Exposed publically
- [ ] Routes requests to internal services
- [ ] Documented
- [ ] Deployed in Kubernetes (#46)
- [ ] Deployed in Mesh (#45)
- [ ] Deploys with management UI
